### PR TITLE
Full rewrite

### PR DESCRIPTION
**Pull request by TangoMan75**
Hi Chris, I'm a big fan of your channel.
I really love your latest video, I want to install all the bests nerdy bootloader themes !
So I thought I'd contribute to your repo. I just did a Shellcheck and cleaned up the script a little.

### CODE REVIEW

**Comment by Not-Qualified** [comment]
@TangoMan75 , I've create on issue on this repository, If You can take a lookout to that issue then that would be Good

**Comment by TangoMan75** [comment]
Hey @Not-Qualified  ! Yeah, I saw it... And then I realised that custom theme doesn't show on my Ubuntu bootloader either :-(

**Comment by Not-Qualified** [comment]
@TangoMan75 , @ChrisTitusTech , then what's the benefit of this, If doesn't show on Distribution such as Ubuntu or KDE Neon

**Comment by TangoMan75** [comment]
Well, seems like Chris code was broken actually... So I rewrote the whole thing and added proper CI/CD, and improved README... And a bunch of stuff.

**Comment by ChrisTitusTech** [comment]
Holy hell, that is one big rewrite, I'll test this out later today and merge it if it works on my systems.

**Pull request closed without merging**
